### ISSUE TITLE
UnboundLocalError: local variable 'p' referenced before assignment

### ISSUE THREAD

**Issue by uzl** [MSC-BUAA/Keras-progressive_growing_of_gans#3]
When I am trying to run
 ` python h5tool.py  create_celeba_channel_last face_dataset.h5 /home/uzzal/dataset/celeba/img_align_celeba` 

I got this error --
`Traceback (most recent call last):
  File "h5tool.py", line 259, in <module>
    execute_cmdline(sys.argv)
  File "h5tool.py", line 241, in execute_cmdline
    p.add_argument(     'h5_filename',      help='HDF5 file to inspect')
UnboundLocalError: local variable 'p' referenced before assignment`

**Comment by progvasu** [comment]
got the same error! 

@uzl were you able to find the cause?

**Comment by JoshBlake** [comment]
It looks like there's an extra line. Comment out this line in h5tool.py on line 242:

```
    #p.add_argument(     'h5_filename',      help='HDF5 file to inspect')

    p = add_command(    'create_celeba_channel_last',    'Create HDF5 channel last dataset for CelebA.',
                                            'create_celeba celeba-128x128.h5 ~/celeba')

    p.add_argument(     'h5_filename',      help='HDF5 file to create')

```
